name: Changelog

on:
  pull_request:
    types: [ "opened", "synchronize" ]

jobs:
  validate-changelog:
    name: Validate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate changelogs
        uses: thiagodnf/yaml-schema-checker@v0.0.8
        with:
          jsonSchemaFile: CHANGELOG/schema.json
          yamlFiles: |
            CHANGELOG/unreleased/*/*.yaml
